import { afterEach, describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { calculateCommission, createAccount, createCustomer, createOrder, createProduct, createReseller, deleteReseller, formatCurrency, getSessionUser, getStore, login, logout, statusLabel, updateOrderDetails, updateOrderStatus, updateReseller, updateResellerInvite, updateStore } from "../client/src/lib/localStore";

const storage = new Map<string, string>();
const fakeWindow = {
  localStorage: { getItem: (key: string) => storage.get(key) ?? null, setItem: (key: string, value: string) => storage.set(key, value) },
  addEventListener: () => undefined,
  removeEventListener: () => undefined,
  dispatchEvent: () => true,
};
Object.defineProperty(globalThis, "window", { value: fakeWindow, writable: true });
afterEach(() => storage.clear());

describe("localStore", () => {
  it("inicia sem dados demonstrativos", () => { const store = getStore(); expect(store.users).toHaveLength(0); expect(store.products).toHaveLength(0); expect(store.orders).toHaveLength(0); expect(store.notifications).toHaveLength(0); });
  it("não reintroduz dados demonstrativos nas interfaces principais", () => { const files = ["LandingPage.tsx", "ManagerDashboard.tsx", "ResellerDashboard.tsx"].map(file => readFileSync(resolve(process.cwd(), "client/src/pages", file), "utf8")).join("\n"); expect(files).toContain("Sem dados"); expect(files).not.toMatch(/18\\.420|18420|12,8|8,4|4,2|10,1|86%|\\+28%|PED-10|Marina Alves|R\\$ 579|R\\$ 173/); });
  it("formata valores e expõe status legível", () => { expect(formatCurrency(189.9)).toContain("189,90"); expect(statusLabel.delivered).toBe("Entregue"); });
  it("cria uma conta e permite login por e-mail", () => { const user = createAccount({ name: "Ana Souza", email: "ana@example.com", phone: "11999990000", password: "123456", role: "gestora", commissionRate: 0 }); expect(user.role).toBe("gestora"); expect(getSessionUser()?.email).toBe("ana@example.com"); logout(); expect(getSessionUser()).toBeNull(); expect(login("ana@example.com", "123456", "gestora").name).toBe("Ana Souza"); });
  it("cria convite novo com link e status pendente", () => { const created = createReseller({ name: "Camila Rocha", city: "Curitiba", inviteLink: "https://example.com/convite/res-new" }); expect(created.inviteLink).toBe("https://example.com/convite/res-new"); expect(created.inviteStatus).toBe("pending"); expect(getStore().users).toHaveLength(1); });
  it("registra uma revendedora e reaproveita o mesmo registro ao convidar novamente", () => { const first = createReseller({ name: "Marina Alves", city: "São Paulo" }); const second = createReseller({ name: " Marina   Alves ", city: "São Paulo" }); expect(second.id).toBe(first.id); expect(getStore().users).toHaveLength(1); const updated = updateResellerInvite(first.id, "https://example.com/convite/res-test"); expect(updated.inviteStatus).toBe("pending"); expect(updated.inviteLink).toContain("res-test"); });
  it("edita dados e impede duplicidade de nome e cidade", () => { const first = createReseller({ name: "Ana Lima", city: "Recife" }); const second = createReseller({ name: "Bia Lima", city: "Natal" }); expect(updateReseller(first.id, { name: "Ana Costa", city: "Olinda" }).city).toBe("Olinda"); expect(() => updateReseller(second.id, { name: "Ana Costa", city: "Olinda" })).toThrow("Já existe"); });
  it("exclui somente a revendedora solicitada", () => { const first = createReseller({ name: "Ana Lima", city: "Recife" }); createReseller({ name: "Bia Lima", city: "Natal" }); expect(deleteReseller(first.id)?.name).toBe("Ana Lima"); expect(getStore().users).toHaveLength(1); });
  it("calcula a comissão com arredondamento monetário", () => { expect(calculateCommission(189.9, 30)).toBe(56.97); expect(calculateCommission(239.8, 12.5)).toBe(29.98); });
  it("impede cadastro duplicado", () => { createAccount({ name: "Ana Souza", email: "ana@example.com", phone: "11999990000", password: "123456", role: "gestora", commissionRate: 0 }); expect(() => createAccount({ name: "Outra Ana", email: "ANA@example.com", phone: "11888880000", password: "123456", role: "gestora", commissionRate: 0 })).toThrow("já está cadastrado"); });
  it("registra pedido direto e baixa estoque sem gerar comissão", () => { const product = createProduct({ name: "Colar Luz", category: "Colares", price: 120, stock: 2, status: "available", accent: "#c8a86b" }); const order = createOrder({ origin: "direct", items: [{ productId: product.id, quantity: 1 }], status: "pending", paymentMethod: "pix", paymentStatus: "paid", saleDate: "2026-08-19T12:00:00.000Z" }); expect(order.origin).toBe("direct"); expect(order.commission).toBe(0); expect(order.items[0]?.subtotal).toBe(120); expect(getStore().products[0]?.stock).toBe(1); });
  it("registra pedido de revendedora, congela comissão e restaura estoque ao cancelar", () => { const reseller = createReseller({ name: "Bia Costa", city: "Recife" }); updateReseller(reseller.id, { name: "Bia Costa", city: "Recife" }); updateStore(next => { const storeUser = next.users.find(user => user.id === reseller.id); if (storeUser) storeUser.commissionRate = 20; }); const product = createProduct({ name: "Anel Essência", category: "Anéis", price: 80, stock: 3, status: "available", accent: "#c8a86b" }); const order = createOrder({ origin: "reseller", resellerId: reseller.id, items: [{ productId: product.id, quantity: 2 }], status: "pending", paymentMethod: "pending", paymentStatus: "pending", saleDate: "2026-08-19T12:00:00.000Z" }); expect(order.commission).toBe(32); expect(order.commissionRate).toBe(20); expect(getStore().products[0]?.stock).toBe(1); updateOrderStatus(order.id, "cancelled"); expect(getStore().products[0]?.stock).toBe(3); });
  it("exige itens e revendedora quando a origem for intermediada", () => { expect(() => createOrder({ entryType: "detailed", origin: "direct", items: [], status: "pending", paymentMethod: "pending", paymentStatus: "pending", saleDate: "2026-08-19T12:00:00.000Z" })).toThrow("ao menos uma peça"); expect(() => createOrder({ entryType: "detailed", origin: "reseller", items: [], status: "pending", paymentMethod: "pending", paymentStatus: "pending", saleDate: "2026-08-19T12:00:00.000Z" })).toThrow("revendedora"); });
  it("registra venda geral sem baixar estoque de peça individual", () => { const product = createProduct({ name: "Brinco Aura", category: "Brincos", price: 60, stock: 4, status: "available", accent: "#c8a86b" }); const order = createOrder({ entryType: "general", origin: "direct", manualDescription: "Venda agregada de peças", manualTotal: 250, items: [], status: "pending", paymentMethod: "cash", paymentStatus: "paid", saleDate: "2026-08-19T12:00:00.000Z" }); expect(order.entryType).toBe("general"); expect(order.items[0]?.productName).toBe("Venda agregada de peças"); expect(order.total).toBe(250); expect(getStore().products.find(item => item.id === product.id)?.stock).toBe(4); });
  it("cadastra cliente uma vez e registra pedido por customerId", () => { const customer = createCustomer({ name: "  Júlia   Martins ", phone: "(11) 99999-0000", email: "JULIA@EXAMPLE.COM" }); const duplicate = createCustomer({ name: "Júlia Martins", phone: "(11) 99999-0000", email: "outra@example.com" }); expect(duplicate.id).toBe(customer.id); expect(getStore().customers).toHaveLength(1); const product = createProduct({ name: "Brinco Cliente", category: "Brincos", price: 75, stock: 1, status: "available", accent: "#c8a86b" }); const order = createOrder({ entryType: "detailed", origin: "direct", customerId: customer.id, items: [{ productId: product.id, quantity: 1 }], status: "pending", paymentMethod: "pix", paymentStatus: "paid", saleDate: "2026-08-19T12:00:00.000Z" }); expect(order.customerId).toBe(customer.id); expect(order.customerName).toBe("Júlia Martins"); expect(order.customerContact).toBe("(11) 99999-0000"); expect(order.notes).toBeUndefined(); expect(order.proofReference).toBeUndefined(); });
  it("mantém os dois fluxos sem os campos removidos e usando customerId", () => { const files = ["ManagerDashboard.tsx", "ResellerDashboard.tsx"].map(file => readFileSync(resolve(process.cwd(), "client/src/pages", file), "utf8")).join("\n"); expect(files).toContain("customerId"); expect(files).not.toContain("customerName:"); expect(files).not.toContain("customerContact:"); expect(files).not.toContain("notes:"); expect(files).not.toContain("proofReference:"); expect(files).not.toContain("Referência do comprovante"); expect(files).not.toContain("Observações internas"); });
  it("edita detalhes permitidos sem alterar itens, estoque ou histórico de status", () => { const customer = createCustomer({ name: "Cliente Edição", phone: "11999990000" }); const product = createProduct({ name: "Brinco Edição", category: "Brincos", price: 70, stock: 2, status: "available", accent: "#c8a86b" }); const order = createOrder({ origin: "direct", customerId: customer.id, items: [{ productId: product.id, quantity: 1 }], status: "pending", paymentMethod: "pending", paymentStatus: "pending", saleDate: "2026-08-19T12:00:00.000Z" }); const itemSnapshot = JSON.stringify(order.items); const historyLength = order.history.length; const updated = updateOrderDetails(order.id, { customerId: customer.id, paymentMethod: "pix", paymentStatus: "paid", saleDate: "2026-08-20T12:00:00.000Z", status: "pending" }); expect(updated.paymentMethod).toBe("pix"); expect(updated.paymentStatus).toBe("paid"); expect(updated.saleDate).toBe("2026-08-20T12:00:00.000Z"); expect(JSON.stringify(updated.items)).toBe(itemSnapshot); expect(updated.history).toHaveLength(historyLength); expect(getStore().products.find(item => item.id === product.id)?.stock).toBe(1); });
  it("é idempotente por requestId e bloqueia transição regressiva", () => { const product = createProduct({ name: "Pulseira Íris", category: "Pulseiras", price: 90, stock: 2, status: "available", accent: "#c8a86b" }); const input = { requestId: "req-fixed-1", entryType: "detailed" as const, origin: "direct" as const, items: [{ productId: product.id, quantity: 1 }], status: "pending" as const, paymentMethod: "pending" as const, paymentStatus: "pending" as const, saleDate: "2026-08-19T12:00:00.000Z" }; const first = createOrder(input); const second = createOrder(input); expect(second.id).toBe(first.id); expect(getStore().products.find(item => item.id === product.id)?.stock).toBe(1); updateOrderStatus(first.id, "approved"); const historyLength = getStore().orders.find(order => order.id === first.id)?.history.length; updateOrderStatus(first.id, "approved"); expect(getStore().orders.find(order => order.id === first.id)?.history.length).toBe(historyLength); expect(() => updateOrderStatus(first.id, "pending")).toThrow("Transição de status inválida"); });
});
