import { useMemo, useState } from "react";
import { ArrowRight, Check, Copy, Grid2X2, Link2, List, MapPin, Pencil, Plus, Search, ShoppingBag, Trash2, UserRound } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import EmptyState from "@/components/EmptyState";
import { createReseller, deleteReseller, updateReseller, updateResellerInvite, type LocalUser } from "@/lib/localStore";
import { buildInviteLink, filterResellers, inviteStatusLabel, normalizeResellerDraft, validateResellerDraft, type InviteStatus } from "./resellerDomain";

type Props = { users: LocalUser[]; onRefresh: () => void; onStartOrder?: (resellerId: string) => void };
type InviteMode = "register" | "invite";
type StatusFilter = "all" | InviteStatus;

export default function ResellersSection({ users, onRefresh, onStartOrder }: Props) {
  const [open, setOpen] = useState(false);
  const [mode, setMode] = useState<InviteMode>("register");
  const [draft, setDraft] = useState({ name: "", city: "" });
  const [inviteLink, setInviteLink] = useState("");
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [cityFilter, setCityFilter] = useState("all");
  const [editing, setEditing] = useState<LocalUser | null>(null);
  const [editDraft, setEditDraft] = useState({ name: "", city: "" });
  const [editError, setEditError] = useState("");
  const [deleting, setDeleting] = useState<LocalUser | null>(null);
  const [viewMode, setViewMode] = useState<"grid" | "list">("grid");
  const [inspecting, setInspecting] = useState<LocalUser | null>(null);

  const cities = useMemo(() => Array.from(new Set(users.map(user => user.city?.trim()).filter(Boolean) as string[])).sort((a, b) => a.localeCompare(b, "pt-BR")), [users]);
  const filteredUsers = useMemo(() => filterResellers(users, query, statusFilter, cityFilter).sort((a, b) => a.name.localeCompare(b.name, "pt-BR")), [cityFilter, query, statusFilter, users]);

  function resetAdd() { setDraft({ name: "", city: "" }); setInviteLink(""); setMode("register"); setError(""); setCopied(false); }
  function closeAdd() { setOpen(false); resetAdd(); }
  function getExisting() { const normalized = normalizeResellerDraft(draft); return users.find(user => user.name.toLocaleLowerCase("pt-BR") === normalized.name.toLocaleLowerCase("pt-BR") && (user.city ?? "").toLocaleLowerCase("pt-BR") === normalized.city.toLocaleLowerCase("pt-BR")); }
  function register() { const result = validateResellerDraft(draft); if (!result.valid) return setError("Preencha Nome e Cidade para continuar."); if (getExisting()) return setError("Esta revendedora já está registrada para esta cidade."); createReseller(result.normalized); onRefresh(); closeAdd(); }
  function invite() { const result = validateResellerDraft(draft); if (!result.valid) return setError("Preencha Nome e Cidade para gerar o convite."); const existing = getExisting(); const link = existing?.inviteLink ?? buildInviteLink(result.normalized); if (existing) updateResellerInvite(existing.id, link); else createReseller({ ...result.normalized, inviteLink: link }); setInviteLink(link); setMode("invite"); setError(""); onRefresh(); }
  async function copyLink() { if (!inviteLink) return; await navigator.clipboard?.writeText(inviteLink); setCopied(true); }
  function openEdit(user: LocalUser) { setEditing(user); setEditDraft({ name: user.name, city: user.city ?? "" }); setEditError(""); }
  function saveEdit() { if (!editing) return; try { updateReseller(editing.id, editDraft); onRefresh(); setEditing(null); } catch (caught) { setEditError(caught instanceof Error ? caught.message : "Não foi possível atualizar."); } }
  function confirmDelete() { if (!deleting) return; deleteReseller(deleting.id); onRefresh(); setDeleting(null); }

  return <section aria-labelledby="resellers-title"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow text-[#9d7d48]">Sua rede</p><h2 id="resellers-title" className="serif mt-2 text-4xl tracking-[-.02em]">Revendedoras</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#69756b]">Cadastre e organize as pessoas que fazem sua marca chegar mais longe.</p></div><Button onClick={() => setOpen(true)} className="rounded-xl bg-[#263b32] text-[#f8f4ed] hover:bg-[#344e42]"><Plus className="mr-2 h-4 w-4" />Adicionar</Button></div>
    <div className="mb-6 grid gap-3 rounded-2xl border border-[#dfd4c3] bg-[#fbf8f3] p-4 md:grid-cols-[minmax(0,1fr)_180px_180px]"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9d7d48]" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar por nome ou cidade" aria-label="Buscar revendedoras" className="border-[#d9cbb6] bg-white pl-9" /></div><Select value={statusFilter} onValueChange={value => setStatusFilter(value as StatusFilter)}><SelectTrigger className="border-[#d9cbb6] bg-white"><SelectValue placeholder="Status" /></SelectTrigger><SelectContent><SelectItem value="all">Todos os status</SelectItem><SelectItem value="not_invited">Sem convite</SelectItem><SelectItem value="pending">Convite pendente</SelectItem><SelectItem value="accepted">Aceito</SelectItem><SelectItem value="expired">Expirado</SelectItem></SelectContent></Select><Select value={cityFilter} onValueChange={setCityFilter}><SelectTrigger className="border-[#d9cbb6] bg-white"><SelectValue placeholder="Cidade" /></SelectTrigger><SelectContent><SelectItem value="all">Todas as cidades</SelectItem>{cities.map(city => <SelectItem key={city} value={city}>{city}</SelectItem>)}</SelectContent></Select></div>
    <div className="mb-5 flex items-center justify-between rounded-2xl border border-[#dfd4c3] bg-[#fbf8f3] p-2"><p className="px-2 text-xs text-[#69756b]">{filteredUsers.length} {filteredUsers.length === 1 ? "revendedora encontrada" : "revendedoras encontradas"}</p><div className="flex rounded-xl border border-[#dfd4c3] bg-white p-1" role="group" aria-label="Visualização das revendedoras"><Button type="button" variant="ghost" size="sm" onClick={() => setViewMode("grid")} className={viewMode === "grid" ? "bg-[#eee4d3] text-[#263b32]" : "text-[#69756b]"} aria-label="Visualização em grade" aria-pressed={viewMode === "grid"}><Grid2X2 className="h-4 w-4" /></Button><Button type="button" variant="ghost" size="sm" onClick={() => setViewMode("list")} className={viewMode === "list" ? "bg-[#eee4d3] text-[#263b32]" : "text-[#69756b]"} aria-label="Visualização em lista" aria-pressed={viewMode === "list"}><List className="h-4 w-4" /></Button></div></div>
    {users.length === 0 ? <EmptyState title="Sua rede está vazia" description="Cadastre uma revendedora ou gere um convite para começar a construir sua rede." /> : filteredUsers.length === 0 ? <EmptyState title="Nenhuma revendedora encontrada" description="Ajuste a busca ou limpe os filtros para visualizar sua rede." /> : <div className={viewMode === "grid" ? "grid gap-4 md:grid-cols-2 xl:grid-cols-3" : "space-y-3"}>{filteredUsers.map(user => viewMode === "grid" ? <ResellerCard key={user.id} user={user} onInspect={() => setInspecting(user)} onEdit={() => openEdit(user)} onDelete={() => setDeleting(user)} onStartOrder={onStartOrder ? () => onStartOrder(user.id) : undefined} /> : <ResellerListCard key={user.id} user={user} onInspect={() => setInspecting(user)} onEdit={() => openEdit(user)} onDelete={() => setDeleting(user)} onStartOrder={onStartOrder ? () => onStartOrder(user.id) : undefined} />)}</div>}
    <ResellerInspector user={inspecting} onClose={() => setInspecting(null)} onStartOrder={onStartOrder} />
    <AddResellerDialog open={open} mode={mode} draft={draft} error={error} inviteLink={inviteLink} copied={copied} onOpenChange={value => value ? setOpen(true) : closeAdd()} onDraftChange={setDraft} onRegister={register} onInvite={invite} onCopy={copyLink} onClose={closeAdd} />
    <Dialog open={Boolean(editing)} onOpenChange={value => !value && setEditing(null)}><DialogContent className="border-[#dfd4c3] bg-[#fbf8f3] sm:max-w-[520px]"><DialogHeader><DialogTitle className="serif text-3xl text-[#263b32]">Editar revendedora</DialogTitle><DialogDescription className="text-[#69756b]">Atualize os dados básicos sem alterar o histórico de convites.</DialogDescription></DialogHeader><div className="space-y-5 py-5"><div><label htmlFor="edit-reseller-name" className="mb-2 block text-sm font-medium text-[#263b32]">Nome</label><Input id="edit-reseller-name" value={editDraft.name} onChange={event => setEditDraft(current => ({ ...current, name: event.target.value }))} className="border-[#d9cbb6] bg-white" /></div><div><label htmlFor="edit-reseller-city" className="mb-2 block text-sm font-medium text-[#263b32]">Cidade</label><Input id="edit-reseller-city" value={editDraft.city} onChange={event => setEditDraft(current => ({ ...current, city: event.target.value }))} className="border-[#d9cbb6] bg-white" /></div>{editError && <p role="alert" className="text-sm text-[#9b6255]">{editError}</p>}</div><DialogFooter><Button variant="outline" onClick={() => setEditing(null)} className="border-[#cdbd9e]">Cancelar</Button><Button onClick={saveEdit} className="bg-[#263b32] text-[#f8f4ed] hover:bg-[#344e42]">Salvar alterações</Button></DialogFooter></DialogContent></Dialog>
    <AlertDialog open={Boolean(deleting)} onOpenChange={value => !value && setDeleting(null)}><AlertDialogContent className="border-[#dfd4c3] bg-[#fbf8f3]"><AlertDialogHeader><AlertDialogTitle className="serif text-2xl text-[#263b32]">Excluir revendedora?</AlertDialogTitle><AlertDialogDescription className="text-[#69756b]">Essa ação remove {deleting?.name ?? "a revendedora"} da lista local. O histórico futuro do backend deverá aplicar suas próprias regras de auditoria.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel className="border-[#cdbd9e]">Cancelar</AlertDialogCancel><AlertDialogAction onClick={confirmDelete} className="bg-[#9b6255] text-white hover:bg-[#854e44]">Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </section>;
}

function AddResellerDialog({ open, mode, draft, error, inviteLink, copied, onOpenChange, onDraftChange, onRegister, onInvite, onCopy, onClose }: { open: boolean; mode: InviteMode; draft: { name: string; city: string }; error: string; inviteLink: string; copied: boolean; onOpenChange: (open: boolean) => void; onDraftChange: (draft: { name: string; city: string }) => void; onRegister: () => void; onInvite: () => void; onCopy: () => void; onClose: () => void }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="border-[#dfd4c3] bg-[#fbf8f3] sm:max-w-[520px]"><DialogHeader><DialogTitle className="serif text-3xl text-[#263b32]">Adicionar revendedora</DialogTitle><DialogDescription className="text-[#69756b]">Registre os dados básicos ou prepare um convite personalizado.</DialogDescription></DialogHeader>{mode === "invite" ? <div className="space-y-4 py-5"><div className="rounded-2xl border border-[#d7bd8c] bg-[#f6efe3] p-4"><div className="flex items-center gap-2 text-sm font-medium text-[#263b32]"><Link2 className="h-4 w-4 text-[#9d7d48]" />Convite preparado</div><p className="mt-2 text-sm leading-6 text-[#69756b]">O link foi gerado a partir dos dados informados e já está salvo na revendedora.</p></div><div className="flex gap-2"><Input readOnly value={inviteLink} aria-label="Link personalizado de convite" className="border-[#d9cbb6] bg-white" /><Button type="button" variant="outline" onClick={onCopy} className="shrink-0 border-[#cdbd9e]">{copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}</Button></div></div> : <div className="space-y-5 py-5"><div><label htmlFor="reseller-name" className="mb-2 block text-sm font-medium text-[#263b32]">Nome <span className="text-[#9d7d48]">obrigatório</span></label><Input id="reseller-name" value={draft.name} onChange={event => onDraftChange({ ...draft, name: event.target.value })} placeholder="Nome da revendedora" className="border-[#d9cbb6] bg-white" /></div><div><label htmlFor="reseller-city" className="mb-2 block text-sm font-medium text-[#263b32]">Cidade <span className="text-[#9d7d48]">obrigatório</span></label><Input id="reseller-city" value={draft.city} onChange={event => onDraftChange({ ...draft, city: event.target.value })} placeholder="Cidade onde atua" className="border-[#d9cbb6] bg-white" /></div>{error && <p role="alert" className="text-sm text-[#9b6255]">{error}</p>}</div>}<DialogFooter>{mode === "invite" ? <Button type="button" onClick={onClose} className="bg-[#263b32] text-[#f8f4ed] hover:bg-[#344e42]">Concluir</Button> : <><Button type="button" variant="outline" onClick={onRegister} className="border-[#cdbd9e] text-[#263b32]">Registrar</Button><Button type="button" onClick={onInvite} className="bg-[#263b32] text-[#f8f4ed] hover:bg-[#344e42]">Convidar via link</Button></>}</DialogFooter></DialogContent></Dialog>; }

function ResellerCard({ user, onInspect, onEdit, onDelete, onStartOrder }: { user: LocalUser; onInspect: () => void; onEdit: () => void; onDelete: () => void; onStartOrder?: () => void }) { const status = (user.inviteStatus ?? (user.active ? "accepted" : "pending")) as InviteStatus; return <article role="button" tabIndex={0} onClick={onInspect} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onInspect(); } }} aria-label={`Inspecionar revendedora ${user.name}`} className="group cursor-pointer rounded-2xl border border-[#dfd4c3] bg-[#fbf8f3] p-5 shadow-[0_12px_28px_rgba(38,59,50,.04)] transition-[border-color,box-shadow,transform] duration-200 hover:-translate-y-px hover:border-[#cdbd9e] hover:shadow-[0_12px_30px_rgba(38,59,50,.10)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#c7a66b]"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full border border-[#d7bd8c] bg-[#e4d6be] text-sm text-[#6f5935]">{user.name.slice(0, 2).toUpperCase()}</div><div><h3 className="font-medium text-[#263b32]">{user.name}</h3><p className="mt-1 flex items-center gap-1 text-xs text-[#69756b]"><MapPin className="h-3.5 w-3.5 text-[#9d7d48]" />{user.city || "Cidade não informada"}</p></div></div><Badge className={status === "accepted" ? "bg-[#e2eee4] text-[#58705d]" : "bg-[#f6efe3] text-[#896b3b]"}>{inviteStatusLabel(status)}</Badge></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-[#eee7dd] pt-4"><div><p className="text-xs text-[#8c9187]">Status do convite</p><p className="mt-1 text-sm text-[#263b32]">{inviteStatusLabel(status)}</p></div><div><p className="text-xs text-[#8c9187]">Comissão</p><p className="mt-1 text-sm text-[#263b32]">{user.commissionRate ? "Configurada" : "A definir"}</p></div></div><div className="mt-5 flex justify-end gap-2 border-t border-[#eee7dd] pt-4">{onStartOrder && <Button variant="outline" size="sm" onClick={event => { event.stopPropagation(); onStartOrder(); }} className="border-[#cdbd9e] text-[#263b32]"><ShoppingBag className="mr-2 h-3.5 w-3.5" />Novo pedido</Button>}<Button variant="outline" size="sm" onClick={event => { event.stopPropagation(); onEdit(); }} className="border-[#cdbd9e] text-[#263b32]"><Pencil className="mr-2 h-3.5 w-3.5" />Editar</Button><Button variant="outline" size="sm" onClick={event => { event.stopPropagation(); onDelete(); }} className="border-[#d8b9b0] text-[#9b6255] hover:bg-[#f5e9e3]"><Trash2 className="mr-2 h-3.5 w-3.5" />Excluir</Button></div></article>; }


function ResellerListCard({ user, onInspect, onEdit, onDelete, onStartOrder }: { user: LocalUser; onInspect: () => void; onEdit: () => void; onDelete: () => void; onStartOrder?: () => void }) {
  const status = (user.inviteStatus ?? (user.active ? "accepted" : "pending")) as InviteStatus;
  return <article role="button" tabIndex={0} onClick={onInspect} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onInspect(); } }} aria-label={`Inspecionar revendedora ${user.name}`} className="group flex cursor-pointer flex-col gap-4 rounded-2xl border border-[#dfd4c3] bg-[#fbf8f3] p-4 transition-[border-color,box-shadow,transform] duration-200 hover:-translate-y-px hover:border-[#cdbd9e] hover:shadow-[0_12px_30px_rgba(38,59,50,.10)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#c7a66b] md:flex-row md:items-center">
    <div className="flex min-w-0 flex-1 items-center gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-[#d7bd8c] bg-[#e4d6be] text-sm text-[#6f5935]">{user.name.slice(0, 2).toUpperCase()}</div><div className="min-w-0"><h3 className="truncate font-medium text-[#263b32]">{user.name}</h3><p className="mt-1 flex items-center gap-1 text-xs text-[#69756b]"><MapPin className="h-3.5 w-3.5 text-[#9d7d48]" />{user.city || "Cidade não informada"}</p></div></div>
    <div className="flex items-center gap-6 text-sm"><div><p className="text-[10px] uppercase tracking-[.1em] text-[#8c9187]">Convite</p><p className="mt-1 text-[#263b32]">{inviteStatusLabel(status)}</p></div><div><p className="text-[10px] uppercase tracking-[.1em] text-[#8c9187]">Comissão</p><p className="mt-1 text-[#263b32]">{user.commissionRate ? "Configurada" : "A definir"}</p></div></div>
    <div className="flex shrink-0 gap-2 border-t border-[#eee7dd] pt-3 md:border-l md:border-t-0 md:pl-4 md:pt-0">{onStartOrder && <Button variant="outline" size="sm" onClick={event => { event.stopPropagation(); onStartOrder(); }} className="border-[#cdbd9e] text-[#263b32]" aria-label={`Novo pedido para ${user.name}`}><ShoppingBag className="h-3.5 w-3.5" /></Button>}<Button variant="outline" size="sm" onClick={event => { event.stopPropagation(); onEdit(); }} className="border-[#cdbd9e] text-[#263b32]" aria-label={`Editar ${user.name}`}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="outline" size="sm" onClick={event => { event.stopPropagation(); onDelete(); }} className="border-[#d8b9b0] text-[#9b6255]" aria-label={`Excluir ${user.name}`}><Trash2 className="h-3.5 w-3.5" /></Button><ArrowRight className="ml-1 hidden h-4 w-4 self-center text-[#9d7d48] transition-transform group-hover:translate-x-1 md:block" aria-hidden="true" /></div>
  </article>;
}

function ResellerInspector({ user, onClose, onStartOrder }: { user: LocalUser | null; onClose: () => void; onStartOrder?: (resellerId: string) => void }) {
  if (!user) return null;
  const status = (user.inviteStatus ?? (user.active ? "accepted" : "pending")) as InviteStatus;
  return <Dialog open onOpenChange={open => !open && onClose()}><DialogContent className="border-[#dfd4c3] bg-[#fbf8f3] sm:max-w-lg"><DialogHeader><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-full border border-[#d7bd8c] bg-[#e4d6be] text-[#6f5935]">{user.name.slice(0, 2).toUpperCase()}</div><div><DialogTitle className="serif text-3xl text-[#263b32]">{user.name}</DialogTitle><DialogDescription className="mt-1 text-[#69756b]">Visão rápida da revendedora e próximos passos.</DialogDescription></div></div></DialogHeader><div className="grid grid-cols-2 gap-3 py-5"><div className="rounded-xl bg-[#eee4d3] p-4"><UserRound className="h-4 w-4 text-[#9d7d48]" /><p className="mt-3 text-xs text-[#69756b]">Cidade</p><p className="mt-1 text-sm font-medium text-[#263b32]">{user.city || "Não informada"}</p></div><div className="rounded-xl bg-[#eee4d3] p-4"><Check className="h-4 w-4 text-[#9d7d48]" /><p className="mt-3 text-xs text-[#69756b]">Status</p><p className="mt-1 text-sm font-medium text-[#263b32]">{inviteStatusLabel(status)}</p></div><div className="rounded-xl bg-[#eee4d3] p-4"><p className="text-xs text-[#69756b]">Comissão</p><p className="mt-1 text-sm font-medium text-[#263b32]">{user.commissionRate ? `${user.commissionRate}% configurada` : "A definir"}</p></div><div className="rounded-xl bg-[#eee4d3] p-4"><p className="text-xs text-[#69756b]">Cadastro</p><p className="mt-1 text-sm font-medium text-[#263b32]">{new Date(user.createdAt).toLocaleDateString("pt-BR")}</p></div></div><DialogFooter><Button variant="outline" onClick={onClose} className="border-[#cdbd9e]">Fechar</Button>{onStartOrder && <Button onClick={() => { onClose(); onStartOrder(user.id); }} className="bg-[#263b32] text-[#f8f4ed] hover:bg-[#344e42]"><ShoppingBag className="mr-2 h-4 w-4" />Novo pedido</Button>}</DialogFooter></DialogContent></Dialog>;
}
