import { useMemo, useState } from "react";
import { Check, Copy, Link2, MapPin, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import EmptyState from "@/components/EmptyState";
import { createReseller, deleteReseller, updateReseller, updateResellerInvite, type LocalUser } from "@/lib/localStore";
import { buildInviteLink, filterResellers, inviteStatusLabel, normalizeResellerDraft, validateResellerDraft, type InviteStatus } from "./resellerDomain";

type Props = { users: LocalUser[]; onRefresh: () => void };
type InviteMode = "register" | "invite";
type StatusFilter = "all" | InviteStatus;

export default function ResellersSection({ users, onRefresh }: Props) {
  const [open, setOpen] = useState(false);
  const [mode, setMode] = useState<InviteMode>("register");
  const [draft, setDraft] = useState({ name: "", city: "" });
  const [inviteLink, setInviteLink] = useState("");
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [cityFilter, setCityFilter] = useState("all");
  const [editing, setEditing] = useState<LocalUser | null>(null);
  const [editDraft, setEditDraft] = useState({ name: "", city: "" });
  const [editError, setEditError] = useState("");
  const [deleting, setDeleting] = useState<LocalUser | null>(null);

  const cities = useMemo(() => Array.from(new Set(users.map(user => user.city?.trim()).filter(Boolean) as string[])).sort((a, b) => a.localeCompare(b, "pt-BR")), [users]);
  const filteredUsers = useMemo(() => filterResellers(users, query, statusFilter, cityFilter).sort((a, b) => a.name.localeCompare(b.name, "pt-BR")), [cityFilter, query, statusFilter, users]);

  function resetAdd() { setDraft({ name: "", city: "" }); setInviteLink(""); setMode("register"); setError(""); setCopied(false); }
  function closeAdd() { setOpen(false); resetAdd(); }
  function getExisting() { const normalized = normalizeResellerDraft(draft); return users.find(user => user.name.toLocaleLowerCase("pt-BR") === normalized.name.toLocaleLowerCase("pt-BR") && (user.city ?? "").toLocaleLowerCase("pt-BR") === normalized.city.toLocaleLowerCase("pt-BR")); }
  function register() { const result = validateResellerDraft(draft); if (!result.valid) return setError("Preencha Nome e Cidade para continuar."); if (getExisting()) return setError("Esta revendedora já está registrada para esta cidade."); createReseller(result.normalized); onRefresh(); closeAdd(); }
  function invite() { const result = validateResellerDraft(draft); if (!result.valid) return setError("Preencha Nome e Cidade para gerar o convite."); const existing = getExisting(); const link = existing?.inviteLink ?? buildInviteLink(result.normalized); if (existing) updateResellerInvite(existing.id, link); else createReseller({ ...result.normalized, inviteLink: link }); setInviteLink(link); setMode("invite"); setError(""); onRefresh(); }
  async function copyLink() { if (!inviteLink) return; await navigator.clipboard?.writeText(inviteLink); setCopied(true); }
  function openEdit(user: LocalUser) { setEditing(user); setEditDraft({ name: user.name, city: user.city ?? "" }); setEditError(""); }
  function saveEdit() { if (!editing) return; try { updateReseller(editing.id, editDraft); onRefresh(); setEditing(null); } catch (caught) { setEditError(caught instanceof Error ? caught.message : "Não foi possível atualizar."); } }
  function confirmDelete() { if (!deleting) return; deleteReseller(deleting.id); onRefresh(); setDeleting(null); }

  return <section aria-labelledby="resellers-title"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow text-[#9d7d48]">Sua rede</p><h2 id="resellers-title" className="serif mt-2 text-4xl tracking-[-.02em]">Revendedoras</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#69756b]">Cadastre e organize as pessoas que fazem sua marca chegar mais longe.</p></div><Button onClick={() => setOpen(true)} className="rounded-xl bg-[#263b32] text-[#f8f4ed] hover:bg-[#344e42]"><Plus className="mr-2 h-4 w-4" />Adicionar</Button></div>
    <div className="mb-6 grid gap-3 rounded-2xl border border-[#dfd4c3] bg-[#fbf8f3] p-4 md:grid-cols-[minmax(0,1fr)_180px_180px]"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9d7d48]" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar por nome ou cidade" aria-label="Buscar revendedoras" className="border-[#d9cbb6] bg-white pl-9" /></div><Select value={statusFilter} onValueChange={value => setStatusFilter(value as StatusFilter)}><SelectTrigger className="border-[#d9cbb6] bg-white"><SelectValue placeholder="Status" /></SelectTrigger><SelectContent><SelectItem value="all">Todos os status</SelectItem><SelectItem value="not_invited">Sem convite</SelectItem><SelectItem value="pending">Convite pendente</SelectItem><SelectItem value="accepted">Aceito</SelectItem><SelectItem value="expired">Expirado</SelectItem></SelectContent></Select><Select value={cityFilter} onValueChange={setCityFilter}><SelectTrigger className="border-[#d9cbb6] bg-white"><SelectValue placeholder="Cidade" /></SelectTrigger><SelectContent><SelectItem value="all">Todas as cidades</SelectItem>{cities.map(city => <SelectItem key={city} value={city}>{city}</SelectItem>)}</SelectContent></Select></div>
    {users.length === 0 ? <EmptyState title="Sua rede está vazia" description="Cadastre uma revendedora ou gere um convite para começar a construir sua rede." /> : filteredUsers.length === 0 ? <EmptyState title="Nenhuma revendedora encontrada" description="Ajuste a busca ou limpe os filtros para visualizar sua rede." /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filteredUsers.map(user => <ResellerCard key={user.id} user={user} onEdit={() => openEdit(user)} onDelete={() => setDeleting(user)} />)}</div>}
    <AddResellerDialog open={open} mode={mode} draft={draft} error={error} inviteLink={inviteLink} copied={copied} onOpenChange={value => value ? setOpen(true) : closeAdd()} onDraftChange={setDraft} onRegister={register} onInvite={invite} onCopy={copyLink} onClose={closeAdd} />
    <Dialog open={Boolean(editing)} onOpenChange={value => !value && setEditing(null)}><DialogContent className="border-[#dfd4c3] bg-[#fbf8f3] sm:max-w-[520px]"><DialogHeader><DialogTitle className="serif text-3xl text-[#263b32]">Editar revendedora</DialogTitle><DialogDescription className="text-[#69756b]">Atualize os dados básicos sem alterar o histórico de convites.</DialogDescription></DialogHeader><div className="space-y-5 py-5"><div><label htmlFor="edit-reseller-name" className="mb-2 block text-sm font-medium text-[#263b32]">Nome</label><Input id="edit-reseller-name" value={editDraft.name} onChange={event => setEditDraft(current => ({ ...current, name: event.target.value }))} className="border-[#d9cbb6] bg-white" /></div><div><label htmlFor="edit-reseller-city" className="mb-2 block text-sm font-medium text-[#263b32]">Cidade</label><Input id="edit-reseller-city" value={editDraft.city} onChange={event => setEditDraft(current => ({ ...current, city: event.target.value }))} className="border-[#d9cbb6] bg-white" /></div>{editError && <p role="alert" className="text-sm text-[#9b6255]">{editError}</p>}</div><DialogFooter><Button variant="outline" onClick={() => setEditing(null)} className="border-[#cdbd9e]">Cancelar</Button><Button onClick={saveEdit} className="bg-[#263b32] text-[#f8f4ed] hover:bg-[#344e42]">Salvar alterações</Button></DialogFooter></DialogContent></Dialog>
    <AlertDialog open={Boolean(deleting)} onOpenChange={value => !value && setDeleting(null)}><AlertDialogContent className="border-[#dfd4c3] bg-[#fbf8f3]"><AlertDialogHeader><AlertDialogTitle className="serif text-2xl text-[#263b32]">Excluir revendedora?</AlertDialogTitle><AlertDialogDescription className="text-[#69756b]">Essa ação remove {deleting?.name ?? "a revendedora"} da lista local. O histórico futuro do backend deverá aplicar suas próprias regras de auditoria.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel className="border-[#cdbd9e]">Cancelar</AlertDialogCancel><AlertDialogAction onClick={confirmDelete} className="bg-[#9b6255] text-white hover:bg-[#854e44]">Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </section>;
}

function AddResellerDialog({ open, mode, draft, error, inviteLink, copied, onOpenChange, onDraftChange, onRegister, onInvite, onCopy, onClose }: { open: boolean; mode: InviteMode; draft: { name: string; city: string }; error: string; inviteLink: string; copied: boolean; onOpenChange: (open: boolean) => void; onDraftChange: (draft: { name: string; city: string }) => void; onRegister: () => void; onInvite: () => void; onCopy: () => void; onClose: () => void }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="border-[#dfd4c3] bg-[#fbf8f3] sm:max-w-[520px]"><DialogHeader><DialogTitle className="serif text-3xl text-[#263b32]">Adicionar revendedora</DialogTitle><DialogDescription className="text-[#69756b]">Registre os dados básicos ou prepare um convite personalizado.</DialogDescription></DialogHeader>{mode === "invite" ? <div className="space-y-4 py-5"><div className="rounded-2xl border border-[#d7bd8c] bg-[#f6efe3] p-4"><div className="flex items-center gap-2 text-sm font-medium text-[#263b32]"><Link2 className="h-4 w-4 text-[#9d7d48]" />Convite preparado</div><p className="mt-2 text-sm leading-6 text-[#69756b]">O link foi gerado a partir dos dados informados e já está salvo na revendedora.</p></div><div className="flex gap-2"><Input readOnly value={inviteLink} aria-label="Link personalizado de convite" className="border-[#d9cbb6] bg-white" /><Button type="button" variant="outline" onClick={onCopy} className="shrink-0 border-[#cdbd9e]">{copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}</Button></div></div> : <div className="space-y-5 py-5"><div><label htmlFor="reseller-name" className="mb-2 block text-sm font-medium text-[#263b32]">Nome <span className="text-[#9d7d48]">obrigatório</span></label><Input id="reseller-name" value={draft.name} onChange={event => onDraftChange({ ...draft, name: event.target.value })} placeholder="Nome da revendedora" className="border-[#d9cbb6] bg-white" /></div><div><label htmlFor="reseller-city" className="mb-2 block text-sm font-medium text-[#263b32]">Cidade <span className="text-[#9d7d48]">obrigatório</span></label><Input id="reseller-city" value={draft.city} onChange={event => onDraftChange({ ...draft, city: event.target.value })} placeholder="Cidade onde atua" className="border-[#d9cbb6] bg-white" /></div>{error && <p role="alert" className="text-sm text-[#9b6255]">{error}</p>}</div>}<DialogFooter>{mode === "invite" ? <Button type="button" onClick={onClose} className="bg-[#263b32] text-[#f8f4ed] hover:bg-[#344e42]">Concluir</Button> : <><Button type="button" variant="outline" onClick={onRegister} className="border-[#cdbd9e] text-[#263b32]">Registrar</Button><Button type="button" onClick={onInvite} className="bg-[#263b32] text-[#f8f4ed] hover:bg-[#344e42]">Convidar via link</Button></>}</DialogFooter></DialogContent></Dialog>; }

function ResellerCard({ user, onEdit, onDelete }: { user: LocalUser; onEdit: () => void; onDelete: () => void }) { const status = (user.inviteStatus ?? (user.active ? "accepted" : "pending")) as InviteStatus; return <article className="rounded-2xl border border-[#dfd4c3] bg-[#fbf8f3] p-5 shadow-[0_12px_28px_rgba(38,59,50,.04)]"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full border border-[#d7bd8c] bg-[#e4d6be] text-sm text-[#6f5935]">{user.name.slice(0, 2).toUpperCase()}</div><div><h3 className="font-medium text-[#263b32]">{user.name}</h3><p className="mt-1 flex items-center gap-1 text-xs text-[#69756b]"><MapPin className="h-3.5 w-3.5 text-[#9d7d48]" />{user.city || "Cidade não informada"}</p></div></div><Badge className={status === "accepted" ? "bg-[#e2eee4] text-[#58705d]" : "bg-[#f6efe3] text-[#896b3b]"}>{inviteStatusLabel(status)}</Badge></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-[#eee7dd] pt-4"><div><p className="text-xs text-[#8c9187]">Status do convite</p><p className="mt-1 text-sm text-[#263b32]">{inviteStatusLabel(status)}</p></div><div><p className="text-xs text-[#8c9187]">Comissão</p><p className="mt-1 text-sm text-[#263b32]">{user.commissionRate ? "Configurada" : "A definir"}</p></div></div><div className="mt-5 flex justify-end gap-2 border-t border-[#eee7dd] pt-4"><Button variant="outline" size="sm" onClick={onEdit} className="border-[#cdbd9e] text-[#263b32]"><Pencil className="mr-2 h-3.5 w-3.5" />Editar</Button><Button variant="outline" size="sm" onClick={onDelete} className="border-[#d8b9b0] text-[#9b6255] hover:bg-[#f5e9e3]"><Trash2 className="mr-2 h-3.5 w-3.5" />Excluir</Button></div></article>; }
